
// import { Metadata } from "next";
// import "./globals.css";
// import { Inter } from "next/font/google";
// import Navbar from "../components/Navbar";
// import ShowComponents from "../components/ShowComponents";
// import Footer from "../components/Footer";
// import { AppProvider } from "@/context/AppContext";
// import { Auth0Provider } from "@auth0/auth0-react";
// import { useRouter } from "next/navigation";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Kazuo",
//   description: "Generated by create next app",
// };

// interface RootLayoutProps {
//   children: React.ReactNode;
// }

// export default function RootLayout({ children }: RootLayoutProps) {
//   return (

//     <html lang="en">
//       <body className={inter.className}>
    
      

//         <AppProvider>
//         <ShowComponents>
//         <Navbar/>
//         </ShowComponents>
//         {children}
//         <Footer />
//         </AppProvider>
     
        

//       </body>
//     </html>
//   );
// }

import { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import ShowComponents from "../components/ShowComponents";
import Footer from "../components/Footer";
import { AppProvider } from "@/context/AppContext";
import { Auth0Provider } from "@auth0/auth0-react";
import { useRouter } from "next/navigation";
import ClientLayout from "./ClientLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kazuo",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {

  


  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLayout>

          <AppProvider>
            <ShowComponents>
              <Navbar />
            </ShowComponents>
            {children}
            <Footer />
          </AppProvider>
        </ClientLayout>
        
      </body>
    </html>
  );
}

