import { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import ShowComponents from "../components/ShowComponents";
import Footer from "../components/Footer";
import { AppProvider } from "@/context/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kazuo",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AuthProvider> */}
        <AppProvider>
        <ShowComponents>
        <Navbar/>
        </ShowComponents>
        {children}
        <Footer />
        </AppProvider>
{/* </AuthProvider> */}
      </body>
    </html>
  );
}


