import { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import ShowComponents from "../components/ShowComponents";
import Footer from "../components/Footer";
import { AppProvider } from "@/context/AppContext";
import { Auth0Provider } from "@auth0/auth0-react";
import { useRouter } from "next/navigation";
import ClientLayout from "./ClientLayout";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kazuo",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
     
        <ClientLayout>
          <AppProvider>
            <ShowComponents>
              <Navbar />
            </ShowComponents>
            <Suspense fallback={<div>Loading...</div>}>
          {children}
        </Suspense>            <Footer />
          </AppProvider>
        </ClientLayout>
        
      </body>
    </html>
  );
}
